version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - db_vol:/var/lib/postgresql/data/
    
  api:
    container_name: api
    build: .
    ports:
      - 8888:8888
    

volumes:
  db_vol: